#!/usr/bin/env python3
"""Parse raw_notes.txt into cards.js for the webapp."""
import json
import re
import sys
from pathlib import Path

RAW = Path(__file__).parent / "raw_notes.txt"
OUT = Path(__file__).parent / "cards.js"

def normalize_question(line):
    """Strip leading number prefixes like '1. ' or '12.'."""
    return re.sub(r"^\d+\.\s*", "", line).strip()

def is_question(line):
    """Detect a question line.

    Question lines start with 'What if' (case-insensitive, accent-tolerant)
    and end with '?'. This avoids matching short 'Right?' or similar
    sentences at the end of descriptions.
    """
    if not line.endswith("?"):
        return False
    # Normalize accented 'á' to plain 'a' so typos like 'Whát if' still match.
    lowered = line.lower().replace("á", "a")
    return lowered.startswith("what if")

def parse_category(text):
    cards = []
    lines = [l.strip() for l in text.split("\n")]
    lines = [l for l in lines if l]  # drop blanks

    # Strip stray 'Triggers cards' header lines
    lines = [l for l in lines if l != "Triggers cards"]

    # Normalize numbered-list prefixes on every line (safe — cards never start with a number)
    lines = [re.sub(r"^\d+\.\s*", "", l) for l in lines]

    current_q = None
    current_d = []
    for line in lines:
        if is_question(line):
            if current_q is not None:
                cards.append({
                    "q": current_q,
                    "d": " ".join(current_d).strip()
                })
            current_q = line
            current_d = []
        else:
            current_d.append(line)
    if current_q is not None:
        cards.append({
            "q": current_q,
            "d": " ".join(current_d).strip()
        })
    return cards

def main():
    raw = RAW.read_text(encoding="utf-8")

    # Split by '=== CATEGORY: X ===' delimiters
    parts = re.split(r"^=== CATEGORY:\s*(.+?)\s*===$", raw, flags=re.MULTILINE)
    # parts structure: ['', cat1, body1, cat2, body2, ...]

    if len(parts) < 3:
        print("ERROR: No category delimiters found.", file=sys.stderr)
        sys.exit(1)

    result = {}
    it = iter(parts[1:])
    for cat in it:
        body = next(it)
        result[cat] = parse_category(body)

    # Report counts
    total = 0
    print("Category counts:")
    for cat, cards in result.items():
        print(f"  {cat}: {len(cards)}")
        total += len(cards)
    print(f"Total: {total} cards across {len(result)} categories")

    # Sanity checks
    issues = []
    for cat, cards in result.items():
        if not (55 <= len(cards) <= 65):
            issues.append(f"  {cat}: expected ~60, got {len(cards)}")
        for i, card in enumerate(cards):
            if not card["q"]:
                issues.append(f"  {cat}[{i}]: empty question")
            if not card["d"]:
                issues.append(f"  {cat}[{i}]: empty description (q={card['q']!r})")
            if len(card["d"]) < 10:
                issues.append(f"  {cat}[{i}]: suspiciously short description ({card['d']!r})")

    if issues:
        print("\nISSUES:")
        for i in issues:
            print(i)
    else:
        print("\nAll checks passed.")

    # Write cards.js (kept as a standalone file for reference / easy editing)
    js_content = (
        "// Triggers Cards data — auto-generated by parse.py\n"
        "// Regenerate by running: python3 parse.py\n"
        "window.CARDS_DATA = "
        + json.dumps(result, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT.write_text(js_content, encoding="utf-8")
    print(f"\nWrote {OUT.name} ({OUT.stat().st_size:,} bytes)")

    # Also update index.html to embed the data inline, so the file is fully
    # self-contained (works in previews, works locally by double-clicking,
    # works on any static host).
    index_path = Path(__file__).parent / "index.html"
    if index_path.exists():
        html = index_path.read_text(encoding="utf-8")
        import re as _re
        # Replace whatever is inside the data-script block (whether it's a
        # <script src="cards.js"> tag or a previously-inlined block) with the
        # fresh inlined data.
        inline_block = "<script>\n" + js_content.rstrip() + "\n</script>"
        # Match: either <script src="cards.js"></script>
        # or:    <script> ...CARDS_DATA... </script>
        patterns = [
            r'<script\s+src="cards\.js"></script>',
            r'<script>\s*(?://[^\n]*\n)*\s*window\.CARDS_DATA\s*=\s*\{.*?\};\s*</script>',
        ]
        replaced = False
        for p in patterns:
            new_html, n = _re.subn(p, lambda m: inline_block, html, count=1, flags=_re.S)
            if n:
                html = new_html
                replaced = True
                break
        if replaced:
            index_path.write_text(html, encoding="utf-8")
            print(f"Updated {index_path.name} ({index_path.stat().st_size:,} bytes, data inlined)")
        else:
            print("WARN: Could not find the data-script block in index.html to inline into.")

if __name__ == "__main__":
    main()
